import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Mau apa</h1>
        <ul>
          <li><Link href='/campaign'>Campaign</Link></li>
          <li><Link href='/blog'>Blog</Link></li>
          {/* <li><Link href='/volume'>Volume</Link></li>
          <li><Link href='/set'>Set</Link></li> */}
        </ul>
      </main>
    </>
  )
}
